# Generated by Django 5.0 on 2023-12-23 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenPortada', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'ordering': ['-fechaPublicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.pelicula')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
