# Generated by Django 5.0 on 2023-12-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=200),
        ),
    ]
