# Generated by Django 5.0 on 2023-12-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pelicula_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=400),
        ),
    ]
